name: Auto-add issues to project

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/GoosK67/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}